### ISSUE TITLE
What is max_track_since_new?

### ISSUE THREAD

**Issue by ahmadreza9** [hongzimao/deeprm#15]
Mr. Mao,
Could you explain more what exactly the below parameter do in the parameters class? (I appreciate you if you give me an example.)
https://github.com/hongzimao/deeprm/blob/b42eff0ab843c83c2b1b8d44e65f99440fa2a543/parameters.py#L31

**Comment by ahmadreza9** [comment]
Is it "Maximum time steps which the scheduler tracks each job and waits for its allocation on the data center based on its policy (The maximum number of Move on action which the scheduler can choose.)"?

**Comment by hongzimao** [comment]
If I remember it correctly, this variable is just for normalization of a parameter, so that the neural network would have an easier time to process: https://github.com/hongzimao/deeprm/blob/b42eff0ab843c83c2b1b8d44e65f99440fa2a543/environment.py#L106-L107

**Comment by guyam2** [comment]
Thanks @hongzimao , and if I may add a question to @ahmadreza9 's issue (because this line is coincidentally related  to my current work:

- in many cases this line eventually affects the last input column (the "extra" column) with _time since last new job_ , and receives a value between 0 and 1 - always. Both these claim are correct, right?
- in case the resources (CPUs, memory units etc) are **currently** utilized in some way (some value between 1%-100%) - the extra column in the input  with _time since last new job_  - is always with "0"-fixed values, correct?

Thank you very much for your time an effort!!

**Comment by hongzimao** [comment]
Thanks for your questions @guyam2. 

- last input column is affected by `time_since_last_new_job` as time goes by. The received value might be more than 1, if `time_since_last_new_job` grows larger than `self.extra_info.max_tracking_time_since_last_job`. I was just using a sane value for normalization from (eyeballing) experience (have to admit it's not the best way of doing normalization..)
- no, a job might come and takes some time to finish, during which if no new jobs arrive, the `time_since_last_new_job`  counter will grow. For example, let's say a job arrives at time `t`, it runs until `t + 4`, during [`t`, `t+4`] no other jobs arrive, then at `t`, `time_since_last_new_job` will be 0, but at `t+2`, `time_since_last_new_job` will be 2. 

Hope these are helpful!

**Comment by guyam2** [comment]
Thanks @hongzimao! Your help is much appreciated
